---

- name: Deploy Plantation Station
  hosts: all
  tasks:
  - name: cd to repo directory
    shell: cd ~/plantation_station && git pull

  - name: sync packages
    shell: /usr/local/bin/poetry run autonomy packages sync
    become: yes

  - name: stop plantation service
    shell: systemctl stop agent.service
    become: yes

  - name: stop tendermint service
    shell: systemctl stop tendermint.service
    become: yes

  - name: remove tendermint directory
    shell: rm -rf ~/.tendermint

  - name: remove agent directory
    shell: rm -rf ~/plantation_station/agent

  - name: init tendermint
    shell: tendermint init
    become: yes

  - name: start tendermint service
    shell: systemctl start tendermint.service
    become: yes

  - name: start plantation service
    shell: systemctl start agent.service