name: Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    continue-on-error: False
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get a specific Node.js version such that hardhat does not hang periodically
        uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"

      # Install modules
      - name: Install modules
        run: yarn install

      # Run linters
      - name: Run ESLint
        run: ./node_modules/.bin/eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run solhint
        run: ./node_modules/.bin/solhint contracts/*.sol contracts/test/*.sol

      # Compile the code and run tests and deploy script(s)
      - name: Compile the code
        run: ./node_modules/.bin/hardhat compile
      - name: Run tests
        run: ./node_modules/.bin/hardhat test

      # Run hardhat coverage and upload codecov report
      - name: Solidity coverage summary
        run: ./node_modules/.bin/hardhat coverage