name: plantation_station
author: eightballer
version: 0.1.0
description: An agent service to autonomously grow and harvest crops.
aea_version: '>=1.0.0, <2.0.0'
license: Apache-2.0
fingerprint: {}
fingerprint_ignore_patterns: []
agent: zarathustra/plantation:0.1.0:bafybeiaimvkdlbxxto4dteryv2g6nkeed2xjoqcieu47n4xlvtrpfnabi4
number_of_agents: 1
deployment: {}
